dflt:
  nmake -f TrayTest.mak CFG="TrayTest - Win32 Debug"

dbg:
  nmake -f TrayTest.mak CFG="TrayTest - Win32 Debug"

rel:
  nmake -f TrayTest.mak CFG="TrayTest - Win32 Release"

all:  dbg rel
 
