dflt:
  nmake -f MoveDlg.mak CFG="MoveDlg - Win32 Debug"

dbg:
  nmake -f MoveDlg.mak CFG="MoveDlg - Win32 Debug"

rel:
  nmake -f MoveDlg.mak CFG="MoveDlg - Win32 Release"

all:  dbg rel
  
